-- MySQL Script generated by MySQL Workbench
-- Thu Jun  1 20:00:18 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema social_network
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema social_network
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `social_network` DEFAULT CHARACTER SET utf8 ;
USE `social_network` ;

-- -----------------------------------------------------
-- Table `social_network`.`Profile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `social_network`.`Profile` (
  `id` INT NOT NULL,
  `full_name` VARCHAR(45) NOT NULL,
  `date_of_birth` DATETIME NULL,
  `gender` VARCHAR(45) NULL,
  `bio` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `social_network`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `social_network`.`User` (
  `id` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `registration_date` DATETIME NOT NULL,
  `user_profile_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_User_Profile_idx` (`user_profile_id` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`email` ASC) VISIBLE,
  CONSTRAINT `fk_User_Profile`
    FOREIGN KEY (`user_profile_id`)
    REFERENCES `social_network`.`Profile` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `social_network`.`Friendship`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `social_network`.`Friendship` (
  `id` INT NOT NULL,
  `friend_profile_id` INT NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `friend_profile_id_idx` (`friend_profile_id` ASC) VISIBLE,
  CONSTRAINT `friend_profile_id`
    FOREIGN KEY (`friend_profile_id`)
    REFERENCES `social_network`.`Profile` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `social_network`.`Post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `social_network`.`Post` (
  `id` INT NOT NULL,
  `date_created` DATETIME NOT NULL,
  `poster_profile_id` INT NOT NULL,
  `content` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Post_Profile1_idx` (`poster_profile_id` ASC) VISIBLE,
  CONSTRAINT `fk_Post_Profile1`
    FOREIGN KEY (`poster_profile_id`)
    REFERENCES `social_network`.`Profile` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `social_network`.`Comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `social_network`.`Comment` (
  `id` INT NOT NULL,
  `commented_post_id` INT NOT NULL,
  `author_profile_id` INT NOT NULL,
  `content` VARCHAR(45) NOT NULL,
  `date_created` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Comment_Post1_idx` (`commented_post_id` ASC) VISIBLE,
  INDEX `author_profile_id_idx` (`author_profile_id` ASC) VISIBLE,
  CONSTRAINT `fk_Comment_Post1`
    FOREIGN KEY (`commented_post_id`)
    REFERENCES `social_network`.`Post` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `author_profile_id`
    FOREIGN KEY (`author_profile_id`)
    REFERENCES `social_network`.`Profile` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `social_network`.`Like`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `social_network`.`Like` (
  `id` INT NOT NULL,
  `liked_post_id` INT NOT NULL,
  `liker_profile_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Like_Post1_idx` (`liked_post_id` ASC) VISIBLE,
  INDEX `profile_id_idx` (`liker_profile_id` ASC) VISIBLE,
  CONSTRAINT `fk_Like_Post1`
    FOREIGN KEY (`liked_post_id`)
    REFERENCES `social_network`.`Post` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `liker_profile_id`
    FOREIGN KEY (`liker_profile_id`)
    REFERENCES `social_network`.`Profile` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `social_network`.`Group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `social_network`.`Group` (
  `id` INT NOT NULL,
  `group_name` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `social_network`.`Group_Membership`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `social_network`.`Group_Membership` (
  `id` INT NOT NULL,
  `member_profile_id` INT NOT NULL,
  `role` VARCHAR(45) NULL,
  `group_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `profile_id_idx` (`member_profile_id` ASC) VISIBLE,
  INDEX `fk_Group_Membership_Group1_idx` (`group_id` ASC) VISIBLE,
  CONSTRAINT `member_profile_id`
    FOREIGN KEY (`member_profile_id`)
    REFERENCES `social_network`.`Profile` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `group_id`
    FOREIGN KEY (`group_id`)
    REFERENCES `social_network`.`Group` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `social_network`.`Message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `social_network`.`Message` (
  `id` INT NOT NULL,
  `receiver_profile_id` INT NOT NULL,
  `content` VARCHAR(45) NULL,
  `date_sent` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `receiver_profil_id_idx` (`receiver_profile_id` ASC) VISIBLE,
  CONSTRAINT `receiver_profile_id`
    FOREIGN KEY (`receiver_profile_id`)
    REFERENCES `social_network`.`Profile` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `social_network`.`Profile_Tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `social_network`.`Profile_Tag` (
  `id` INT NOT NULL,
  `tagged_profile_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `tagged_profile_id_idx` (`tagged_profile_id` ASC) VISIBLE,
  CONSTRAINT `tagged_profile_id`
    FOREIGN KEY (`tagged_profile_id`)
    REFERENCES `social_network`.`Profile` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `social_network`.`Photo_Album`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `social_network`.`Photo_Album` (
  `id` INT NOT NULL,
  `album_profile_id` INT NOT NULL,
  `photo_album_name` VARCHAR(45) NULL,
  `date_created` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Photo_Album_Profile1_idx` (`album_profile_id` ASC) VISIBLE,
  CONSTRAINT `fk_Photo_Album_Profile1`
    FOREIGN KEY (`album_profile_id`)
    REFERENCES `social_network`.`Profile` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `social_network`.`Photo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `social_network`.`Photo` (
  `id` INT NOT NULL,
  `photo_album_id` INT NOT NULL,
  `owner_profile_id` INT NOT NULL,
  `content` BLOB NULL,
  `caption` VARCHAR(45) NULL,
  `upload_date` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Photo_Photo_Album1_idx` (`photo_album_id` ASC) VISIBLE,
  INDEX `owner_profile_id_idx` (`owner_profile_id` ASC) VISIBLE,
  CONSTRAINT `fk_Photo_Photo_Album1`
    FOREIGN KEY (`photo_album_id`)
    REFERENCES `social_network`.`Photo_Album` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `owner_profile_id`
    FOREIGN KEY (`owner_profile_id`)
    REFERENCES `social_network`.`Profile` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `social_network`.`Post_Photo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `social_network`.`Post_Photo` (
  `post_id` INT NOT NULL,
  `photo_id` INT NOT NULL,
  INDEX `fk_Post_has_Photo_Photo1_idx` (`photo_id` ASC) VISIBLE,
  INDEX `fk_Post_has_Photo_Post1_idx` (`post_id` ASC) VISIBLE,
  CONSTRAINT `fk_Post_has_Photo_Post1`
    FOREIGN KEY (`post_id`)
    REFERENCES `social_network`.`Post` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Post_has_Photo_Photo1`
    FOREIGN KEY (`photo_id`)
    REFERENCES `social_network`.`Photo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
